### ISSUE TITLE
vue verus react

### ISSUE THREAD

**Issue by ghost** [johanbrandhorst/gopherjs-grpc-websocket#1]
This repo uses vuejs and your newer stuff uses react.

I tried the react / gopherjs and found it pretty amazing but still lots of code to scaffold / code gen.
VueJS seems simpler and realyl well supported.

DO you think that GRPC using GRPC-Web with vuejs / gopherJs is viable ? 
Or did you move to the react version for specific reasons ?

I am building a ton of GUI and would appreciate someone elses learnings on this... hope you dont mind

**Comment by johanbrandhorst** [comment]
Hi @gedw99. This repo was the first experiment I made with GopherJS, and I chose Vue because, as you say, it is very easy to get started with. Personally I would not use Vue with GopherJS for a large GopherJS project as I found the support lacking and the libraries old. I would chose React or Vecty.

The reason I used Vue here and React for grpcweb-example was to try out different libraries. My next GopherJS project will use Vecty for sure :).

Closing this issue as it is unrelated to this repo. Please find me on twitter (@johanbrandhorst) or Gophers slack (jbrandhorst) if you want to ask more questions.

**Comment by ghost** [comment]
its nice of your to hear your opinion.. thanks.
I tried Vecty but have my reservations:
- router issues
-  the code base is roting a fair bit. Very few updates maybe one every 2
weeks.. MDC vecty stalled  1 to 2 months ago. Its just not getting traction.
-  maybe it needs peopel like us to use it more. not sure.

the only other one i am hot on is the go.isomorphic  project.
its got some very nice aspects.
https://go.isomorphicgo.org/
